services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nest-auth
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: auth_backend
    ports:
      - "3001:3001"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nest-auth
      JWT_SECRET: secret_123
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: auth_frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:3000
    stdin_open: true